# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Nico Deufemia - CMS"
email: ndeufemia.mmt-b2014@fh-salzburg.ac.at
description: > # this means to ignore newlines until "baseurl:"
  Dieser Blog wurde mit Hilfe von Jekyll, einem der besten und meistverwendeten
  Static-Site-Generatoren erzeugt. In diesem Blog berichte ich über meine Erfahrungen
  mit TYPO3, Drupal und der D3 Übung aus Frontend.
baseurl: "/static-site-generated" # the subpath of your site, e.g. /blog
url: "https://dagopert.github.io/static-site-generated" # the base hostname & protocol for your site
twitter_username: dagopert
github_username:  dagopert

# Build settings
markdown: kramdown
